name: Kotlin Main.kt İş Akışı

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Kotlin Gradle Build
        uses: gradle/gradle-action@v1
        with:
          gradle-version: 7.0.2
          tasks: build

      - name: Testleri Çalıştır
        uses: gradle/gradle-action@v1
        with:
          gradle-version: 7.0.2
          tasks: test

      - name: Sonuçları Yayınla
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build/artifacts
